language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - make $TARGET
