<?php

namespace Shaygan\AffiliateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReferrerUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferrerUrlRepository extends EntityRepository
{
}
