<?php

namespace Shaygan\AffiliateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReferralRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferralRegistrationRepository extends EntityRepository
{

    public function getRegistrationByUser($user)
    {
        return $this->_em
                        ->createQuery('SELECT rr FROM ShayganAffiliateBundle:ReferralRegistration rr '
                                . 'JOIN rr.referrer r '
                                . 'WHERE r.id=:id '
                                . 'ORDER BY rr.id DESC ')
                        ->setParameter("id", $user->getId())
        ;
    }

    public function getRegistrationCountByUser($user)
    {
        return $this->_em
                        ->createQuery('SELECT COUNT(rr) FROM ShayganAffiliateBundle:ReferralRegistration rr '
                                . 'JOIN rr.referrer r '
                                . 'WHERE r.id=:id ')
                        ->setParameter("id", $user->getId())
                        ->getSingleScalarResult()
        ;
    }

}
